accessibility: private
containerPort: 5000
autoscale: enabled
replicas: 10
autoscale: disabled
fqdn: other.sandbox.blendlabs.com

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 1
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /
    port: 5000
  periodSeconds: 5
