accessibility: protected
containerPort: 80
autoscale: enabled

istio:
    enabled: true
    tlsMode: STRICT
    gateway:
        maxReplicas: 15
        minReplicas: 3
        resources:
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                cpu: 200m
                memory: 256Mi
